name: BrowserStack Selenium Tests

on:
  push:
    branches: [main, master]

jobs:
  browserstack-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      BS_USERNAME: ${{ secrets.BS_USERNAME }}
      BS_ACCESS_KEY: ${{ secrets.BS_ACCESS_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium==4.10.0 requests googletrans==4.0.0-rc1

    - name: Run BrowserStack tests
      run: |
        python src/main.py > test_output.log 2>&1

    - name: Upload logs
      uses: actions/upload-artifact@v3
      with:
        name: test-log
        path: test_output.log

    - name: Upload downloaded images
      uses: actions/upload-artifact@v3
      with:
        name: downloaded-images
        path: src/images/
